server {
    # Change to port 8090 to match the exposed port in the Dockerfile
    listen 8090;
    server_name localhost;
    
    # Enable detailed logging
    access_log /dev/stdout;
    error_log /dev/stderr debug;

    # API routes - Leite alles an Next.js weiter, da die Logik nun in app/api/... liegt
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # UI routes
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
#        proxy_cache_bypass $http_upgrade;
    }
}

